### ISSUE TITLE
Update the Models UI

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#100]
- [x] Replace the GPU Slider with an on/off button
- [x] Add controls to allow the user to select the classes they want
- [x] Only show the otsu threshold when a 2 class water/no water model is selected
- [x] Make sure the models can run on any imagery selected by the user regardless of whether it was downloaded by coastseg or not.

Add the latest models 
-----
- [x] 2 class / MNDWI: https://zenodo.org/record/7557080#.Y819vBzMJkg (new)
- [x] 2 class / NDWI: https://zenodo.org/record/7557072#.Y8wSIhzMJkg (new)
----

@dbuscombe-usgs Do you have any models you'd like to not be shown to the user?

**Comment by dbuscombe-usgs** [comment]
I have no models that I would like to hide from the user. For RGB imagery, just remove "s2-landsat78-4class_6950472"

**Comment by 2320sharon** [comment]
I've removed the use data button as well as the model  "s2-landsat78-4class_6950472" in the release of 0.0.26
