### ISSUE TITLE
Remove 'select data folder' button in 'SDS_unet_classifier'

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#102]
There are currently 2 options for applying segmentation models using 'SDS_unet_classifier'. The first is to select a 'data' folder containing imagery downloaded using CoastSeg. The second option is to select a folder of images.

I think it is confusing to have both options, since they both essentially select a folder of images. What is the purpose of two separate workflows? How are they supposed to differ? Ideally, I would vote for only one option, namely, the latter; user selects a folder of images to apply the model to.

Further, with reference to https://github.com/SatelliteShorelines/CoastSeg/issues/101, perhaps this approach needs to be redesigned anyway. If the Zoo models were just called from within `SDS_shoreline.py`, then  the rest of the shoreline mapping codes could be used unmodified

**Comment by 2320sharon** [comment]
I agree that there should be only a single button that's used to select a directory of inputs for the model to run on.

I think we should keep a button to allow the user to select images in case they want to try out some of the models.  That way users have the option to use the models to extract shorelines or just use the models on their downloaded imagery without extracting shorelines.  I think having an easy to use interface for trying out zoo models is a great feature especially if users want to try out a zoo model without worrying about the setup.

**Comment by 2320sharon** [comment]
- [ ] Remove User Data button

**Comment by dbuscombe-usgs** [comment]
Ok we can discuss. I agree it would be good to facilitate users trying multiple models, but that could happen with a single folder of images, so I still think one button for image source is good
