### ISSUE TITLE
Investigate `libmamba` for conda install

### ISSUE THREAD

**Issue by CameronBodine** [SatelliteShorelines/CoastSeg#105]
@dbuscombe-usgs requested I post this.

**Is your feature request related to a problem? Please describe.**
Suggest a recipe for installing CoastSeg with [libmamba](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community) to speed up env installation. This was recommended [here](https://github.com/CameronBodine/PINGMapper/issues/47#issuecomment-1376246401) and I made instructions for it's use [here](https://cameronbodine.github.io/PINGMapper/docs/gettingstarted/Installation.html) for installing PING-Mapper's environment. PING-Mapper's dependency on `gdal` made installation very slow, or impossible for some. `libmamba` dramatically sped the installation process.

**Describe the solution you'd like**
First, update base conda environment with:
```
conda update -n base conda
```
Install `libmamba` in base environment with:
```
conda install -n base conda-libmamba-solver
```
Set `libmamba` as default solver:
```
conda config --set solver libmamba
```
Then install `CoastSeg` as normal, i.g.:
```
conda create --name coastseg python=3.9 -y
conda activate coastseg
conda install -c conda-forge geopandas jupyterlab -y
pip install coastseg
```
and `libmamba` will be used as default conda solver.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dbuscombe-usgs** [comment]
Thanks @CameronBodine we will look into this :pray:

**Comment by dbuscombe-usgs** [comment]
I have tested this and fully switched over to miniconda using mamba (rather than conda and anaconda).
