### ISSUE TITLE
Apply tidal corrections to 2d shoreline vectors

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#108]
Currently, shorelines are extracted as continuous (X, Y, t) data and stored in geojson format (t = time). Then, these data are mapped onto transects, T, at specific {X, Y}. Let's call those locations {XT, YT}, that we represent as position along a line, y, so we express the time-series as y(t),  and stored in csv format. 

Finally, a request has been made to take the transect data, and remap as discontinuous shorelines, indexed by time of image acquisition. This would take all the shoreline transect data from each specific date, and store them, for each t, as (XT, YT). This involves the reverse operation y(t) -->  (XT, YT, t).

We should discuss what format to store data.

**Comment by dbuscombe-usgs** [comment]
This issue here is, how should data be aggregated in time? Shorelines may be pieced together from imagery collected at different times. So, do we want an hourly shoreline? or daily? monthly? yearly?

**Comment by dbuscombe-usgs** [comment]
This is a v2 feature request

**Comment by dbuscombe-usgs** [comment]
I renamed the title to reflect the changing nature of this issue. By now, 

1. we have a reliable way to map waterlines and store geojson files
2. we have another issue that will deal with merging discontinuous waterline segments into a single file/vector https://github.com/Doodleverse/CoastSeg/issues/179
3. we also now have the ability to assign tidal corrections to any point, and are working on implementing the button that would correct transect (1d) waterline data to shoreline data

So, in theory we have all we need to now tackle the problem of applying tide corrections to 2d waterlines, by computing a tide correction for each node (or whatever), then applying the horizontal calculation based on a scalar slope, just like coastsat does.

The difficulty may come in applying the correction orthogonally, i.e. perpendicular to the waterline, which requires an estimate of  curvature or orientation at every point. This is, in effect, like drawing virtual transects that intersect each node of the waterline estimate. Because this requires extra research and/or data, it is a V2 request

**Comment by 2320sharon** [comment]
The shorelines derived from intersecting the extracted shorelines with the transects  mentioned above are saved as the raw_transect_time_series_vectors.geojson and raw_transect_time_series_points.geojson files. These files are derived from the raw_transect_time_series.csv file, which when tide correction is run creates a new version of this file called tidally_corrected_transect_time_series.csv. This file then creates tidally_corrected_transect_time_series_vectors.geojson and tidally_corrected_transect_time_series_points.geojson files which perform the function described in the issue.
