### ISSUE TITLE
add a button to apply tide correction to raw timeseries 

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#109]
CoastSeg will NOT wrap the FES14 workflow, however, we should provide the ability for the user to apply tidal corrections to raw shoreline timeseries

This should exactly replicate the current CoastSat workflow; users generate their own csv file containing tidal corrections, and they are applied to the transect data. A new set of csv files would be generated, one per transect

**Comment by dbuscombe-usgs** [comment]
I will make tide csv files

**Comment by 2320sharon** [comment]
coastseg version 0.0.43 contains buttons that perform tidal corrections. They need to be tested further before closing this issue

**Comment by 2320sharon** [comment]
This feature has been implemented and tested. Closing this issue
