### ISSUE TITLE
doodleverse_utils/prediction_imports/do_seg now accepts 'MODEL' argument

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#110]
In order to add the `segformer` model (see https://github.com/Doodleverse/segmentation_gym/issues/115) , I had to add an input variable to `do_seg`, namely the name of the MODEL

https://github.com/Doodleverse/doodleverse_utils/blob/main/doodleverse_utils/prediction_imports.py#L128

codes in seg2map and coastseg should be updated accordingly

Use https://pypi.org/project/doodleverse-utils/0.0.21/

**Comment by dbuscombe-usgs** [comment]
Use https://pypi.org/project/doodleverse-utils/0.0.23/ (more minor bug fixes for segformer model)

**Comment by 2320sharon** [comment]
Updated to the latest version and added MODEL as a parameter to do_seg
