### ISSUE TITLE
"['id'] not in index" (in "computing cross distance transects" step of extracting shorelines)

### ISSUE THREAD

**Issue by edlazarus** [SatelliteShorelines/CoastSeg#117]
New issue that I suspect is related to the Gulf transects themselves:

Here's a screenshot of the error I've now gotten several times for the FL panhandle – I've been looking at Panama City and the barrier that fronts Tyndall Air Force Base (to the southeast).

<img width="750" alt="IDerror_250323" src="https://user-images.githubusercontent.com/56262802/227741617-e35d2194-fa27-4c2f-865c-66d42673ac2d.png">

Nota bene – I can't scroll to see the end of the error message, but it appears to continue below where it cuts off there...

Everything runs smoothly to the step of "computing cross distance transects" in the "extract shorelines" process:

<img width="863" alt="ExtractingSL" src="https://user-images.githubusercontent.com/56262802/227742039-510d1969-7fa5-46fa-b4ed-b67e404ababe.png">

But then the "['id'] not in index" error blows up. There was a run that took an absolute age to complete (despite involving only about a dozen transects) and the result was a largely empty shoreline csv. I've included it just so you can see it. I can't replicate that run, however, because I wasn't sure if this was all a configuration problem at my end, so I completely wiped and reinstalled `coastseg` from scratch, from the `env` up.

Here is the dep file: [coastseg_deps.txt](https://github.com/SatelliteShorelines/CoastSeg/files/11070177/coastseg_deps.txt)

And in case you're able to reproduce the problem, the various `config` & `extracted_shorelines json` & `geojson` files, zipped:
[config_plus.zip](https://github.com/SatelliteShorelines/CoastSeg/files/11070188/config_plus.zip)

I'm running macOS High Sierra v10.13.6, and using Chrome v111.0.5563.64.

IF this is related to the "Gulf" transect set, then it's another reason why a standardised transect layer would be hugely beneficial. In my experience thus far, the SE transect file is stable.

Here's a copy of the empty `csv` files that were generated, just to show you what they looked like:
[nan_timeseries_raw.csv](https://github.com/SatelliteShorelines/CoastSeg/files/11070194/nan_timeseries_raw.csv)
[transect_time_series.csv](https://github.com/SatelliteShorelines/CoastSeg/files/11070195/transect_time_series.csv)

Thanks, team!

**Comment by 2320sharon** [comment]
Good news Eli! I found the cause of that issue. I'm fixing it right now.

**Comment by 2320sharon** [comment]
- [ ] Make error messages scrollable
- [ ] Add id to gulf transects.geojson
- [ ] If id doesn't exist for a set transects create ids for transects

**Comment by 2320sharon** [comment]
@edlazarus good news! This issue has been fixed in `coastseg 0.0.51`
Try `pip install coastseg==0.0.51` and this should fix your issue.

**Comment by edlazarus** [comment]
Works – confirmed!
 Thanks so much @2320sharon!
