### ISSUE TITLE
Zenodo Release sat_RGB_2class_7779766 Needs  BEST_MODEL.txt file to be Fixed

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#129]
# Zenodo Release To Be Fixed
model: sat_RGB_2class_7779766
link: https://zenodo.org/record/7779766#.ZEMOgnbMKUk
Problem: The  BEST_MODEL.txt  has the incorrect best model file listed it contains the file ` sat4class_rgb_512_v6_fullmodel.h5` instead of `sat2class_rgb_512_v6_fullmodel.h5`.

## Contents of best model.txt
Current Contents:  sat4class_rgb_512_v6_fullmodel.h5
Correct Contents: sat2class_rgb_512_v6_fullmodel.h5

@dbuscombe-usgs it is possible to reupload the bestmodel.txt file or edit it?

**Comment by dbuscombe-usgs** [comment]
I made the fix (apologies for the error). Unfortunately, zenodo won't allow editing of files, and reuploading of any file requires a new release with new doi

https://zenodo.org/record/7865364#.ZEhIqJHMLRY

so codes will have to be updated, both here, and in ZOo

**Comment by 2320sharon** [comment]
I'll update the zenodo id in coastseg. Thank you for fixing this!

**Comment by 2320sharon** [comment]
This has been fixed in coastseg version 0.0.59
`pip install coastseg==0.0.59`
