### ISSUE TITLE
Research Request: Determine best polar tide model to use

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#189]
## Objective

---

Our primary objective is to identify the optimal tide model. Specifically, we need to determine which tide model performs the best and how the tide predictions compare against the "FES2014" model. Furthermore, we should evaluate if there's a need to clip the model to achieve tide predictions in a reasonable time frame.

## Polar Models

---
- **Artic Models Available**
        1. AODTM-5
        2. AOTIM-5
        3. AOTIM-5-2018
        4. Arc2kmTM
        5. Gr1kmTM

- **Preferred Model** : `Arc2kmTM`
    - [Model Location](https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2D21RK6K)
    - [PDF describing model file format](https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A39d08798-cc82-4c92-af1e-55b7a56f79d0)
- **Alternative Model**: `AOTIM-5-2018`
- The 5 means "5km spatial resolution", which is probably fine.

## Research Findings

---

- **Download**: The Arctic models can be downloaded using [arcticdata_tides.py](https://github.com/tsutterley/pyTMD/blob/adedb7324f224f98ece894ef4946ad57ef62c871/scripts/arcticdata_tides.py)
- **Usage**: From the update notes on the [compute_tidal_currents.py](https://github.com/tsutterley/pyTMD/blob/adedb7324f224f98ece894ef4946ad57ef62c871/scripts/compute_tidal_currents.py), I believe we can run the Arctic tide models just like the FES model.
- **Parallelization**: The Arctic tide models aren't listed as valid models on the new parallelized code.

**Comment by dbuscombe-usgs** [comment]
I received input from this from Li Erikson at USGS. FES14 is best for our Merbok region, so I think we can close this
