### ISSUE TITLE
Increase maximum possible reference shoreline buffer setting

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#217]
I'm working at a site where the shoreline has prograded a lot and I have long transects, so I need the buffer to be more than 1000m. 

So, in `coastseg.map_UI`, please could you increase the maximum size of the buffer around ref shoreline to be 2000, instead of 1000? Thanks :)

**Comment by 2320sharon** [comment]
## Tasks

- [ ] Investigate why raising the shoreline reference buffer causes a memory error 

- [ ] Does the raising the shoreline reference buffer causes a memory error in coastsat when calling extract shorelines cause the same behavior

**Comment by FlorisCalkoen** [comment]
For the NL this would be useful as well. I noticed that in my area of interest (Dutch wadden sea) I don't map shorelines for some areas because the coastal system is quite wide there, plus the reference shoreline is not representative for the actual shoreline.

**Comment by dbuscombe-usgs** [comment]
Turns out I never did need need a +/- 1000m reference buffer. That is ridiculous, of course. That was an error on my part. Nobody has a beach that changes by +/- 1000m (a 2km envelope).

**Comment by dbuscombe-usgs** [comment]
@FlorisCalkoen, if the 'global reference shoreline' is not useful for you, you would simply specify your own reference shoreline. The reference shoreline buffer of 1000m is plenty large. It applies in both directions, which gives you a maximum expected horizontal distance of 2000m. Surely that is plenty large enough to capture shoreline changes on any beach.

**Comment by FlorisCalkoen** [comment]
@dbuscombe-usgs, thanks, I was about to say that the problem I ran into was more related to the reference shoreline than the absolute shoreline changes. Manually uploading a reference shoreline would indeed fix this. Wrt 1000m changes you might have some rare cases (e.g., land reclamations in China) that you cannot handle.. but that's really uncommon.
