### ISSUE TITLE
Error: tide model not found

### ISSUE THREAD

**Issue by kvos** [SatelliteShorelines/CoastSeg#236]
hi team, great toolbox, super user friendly. 
I found this error when running the tidal correction part:
![image](https://github.com/Doodleverse/CoastSeg/assets/7217258/0ce4fc3f-2a00-4667-86fb-c13edbd02670)

I've attached my config file in case this helps.
[config.json](https://github.com/Doodleverse/CoastSeg/files/14567791/config.json)

 cheers, kilian

**Comment by 2320sharon** [comment]
Hey Killian, this error message is pretty normal.
CoastSeg is just letting you know it didn't find the tide model and you need to download it.
There is a full guide on how to do that here: https://github.com/SatelliteShorelines/CoastSeg/wiki/09.-How-to-Download-Tide-Model

We should probably update the error message to tell any future users they just need to download the tide model.
