### ISSUE TITLE
Version attribute is missing 

### ISSUE THREAD

**Issue by FlorisCalkoen** [SatelliteShorelines/CoastSeg#243]
ping #openjournals/joss-reviews#6683

Typically a version is specified in the package at `src/<package>/.__init__.py`. See [this](https://github.com/geopandas/geopandas/blob/main/geopandas/__init__.py) more advanced GeoPandas example, that probably uses versioneer. But simpler approaches exist as well. See for example: https://py-pkgs.org/07-releasing-versioning

Currently this doesn't work: 
```python
>>> import coastseg
>>> coastseg.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'coastseg' has no attribute '__version__'
>>>
```

**Comment by 2320sharon** [comment]
Hi Floris,

Thanks for pointing this out. I added  the code below to `src>coastseg>__init__.py` and now the code will print the coastseg version. I'll update the next patch release to include this code so any release past 1.2.3 will have this available

![image](https://github.com/SatelliteShorelines/CoastSeg/assets/61564689/ddf43681-581b-4bb7-95e1-9c2e735451cd)


```
from importlib.metadata import version
__version__ = version("coastseg")

```
