### ISSUE TITLE
Multiple and different installation instructions

### ISSUE THREAD

**Issue by FlorisCalkoen** [SatelliteShorelines/CoastSeg#244]
ping #openjournals/joss-reviews#6683

The installation instructions [here](https://github.com/SatelliteShorelines/CoastSeg/wiki/01.-How-to-Install-CoastSeg#mac-users) are different than [these](https://satelliteshorelines.github.io/CoastSeg/basic-install-guide/). I would prefer a conda install, but I think it's important to maintain your instructions at one place and make sure that they are consistent.

**Comment by 2320sharon** [comment]
Hi Floris,
Thank you for raising this issue. I need to decommission the old coastseg wiki since we have moved all the install instructions to the website. I'll take care of that today.

**Comment by 2320sharon** [comment]
All of the installation instructions along with the wiki have all been migrated to the official CoastSeg website.  I also added specific [installation instructions for Mac users](https://satelliteshorelines.github.io/CoastSeg/mac-install-guide/).
