### ISSUE TITLE
Small edit to git clone command in documentation 

### ISSUE THREAD

**Issue by fmemuir** [SatelliteShorelines/CoastSeg#250]
For: https://github.com/openjournals/joss-reviews/issues/6683

Very minor issue, but trying to clone the repo using `git clone coastseg --depth 1 https://github.com/Doodleverse/CoastSeg.git` gives the error:
`fatal: repository 'coastseg' does not exist` 
if the user has not made a folder called 'coastseg' first. Probably better to just have the command as:
`git clone --depth 1 https://github.com/Doodleverse/CoastSeg.git`
as a folder called 'CoastSeg' then gets created anyway.

**Comment by 2320sharon** [comment]
Hi @fmemuir 

Thank you for reviewing CoastSeg. I'll update the documentation with this change.

**Comment by 2320sharon** [comment]
Thank you for this suggestion its much more convenient to have a single CoastSeg folder for most users. The website is now updated with the new git clone command you suggested here. I appreciate it!
