### ISSUE TITLE
CoastSeg paper comments and edits

### ISSUE THREAD

**Issue by fmemuir** [SatelliteShorelines/CoastSeg#256]
For: https://github.com/openjournals/joss-reviews/issues/6683

I'm attaching here an [annotated PDF](https://github.com/SatelliteShorelines/CoastSeg/files/15401873/10.21105.joss.06683_FMannotated.pdf) of the paper for review. The suggestions are minor and mainly grammatical, so I will hold off checking the last few tasks in the "Software paper" part of my checklist until these are addressed. One of my comments was on the referencing style, @cheginit is it customary for JOSS referencing to have papers with four authors appear in-text as "Lastname1, Lastname2 et al., 2020"? If so, please ignore those comments!

**Comment by cheginit** [comment]
> is it customary for JOSS referencing to have papers with four authors appear in-text as "Lastname1, Lastname2 et al., 2020"?

Yes, since there are two papers by the same first author and the same year, the second one is added to distinguish the two references.

**Comment by 2320sharon** [comment]
Hi @fmemuir 

Thank you for reviewing the CoastSeg manuscript. I've updated the CoastSeg manuscript with all of your suggested edits as well as the some of the edits suggested Floris Calkoen.
