### ISSUE TITLE
Double check coastseg/filters/get_kmeans_cluster

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#259]
I'm a little worried that https://github.com/SatelliteShorelines/CoastSeg/blob/5f586866d0cdcddf1a5b70ee373ac7c7158b9d16/src/coastseg/filters.py#L111 does not check the ordering of zero and one in the output

When I drafted this code, I think I had an extra bit of code that switched the labels over, if the 0-label had a smaller average rmse than the 1-label.

If you look at the last lines that compute the scores

```
    scores = [
        np.mean(np.array(rmse)[labels == 0]),
        np.mean(np.array(rmse)[labels == 1]),
    ]
```
it remains possible that the 0-class is actually the 'good' class. I think this only works if 0=bad, and 1=good. Therefore, I propose the additional code before the `return` statement

```
    if scores[0]>scores[1]:
        labels = 1-labels
```

**Comment by 2320sharon** [comment]
I'll add this bit of code into the zoo workflow. Thanks for bringing it up

**Comment by 2320sharon** [comment]
@dbuscombe-usgs 

I think the code you suggested is actually swapping the good and bad labels. Here's why.

In `get_good_bad_files` the list of good and bad files is determined with the lines of code below:
```
    files_bad = np.array(files)[labels == np.argmax(scores)]
    files_good = np.array(files)[labels == np.argmin(scores)]
```
Scores is structured such that scores[0]: is the average RMSE score of all the labels in cluster 0 and the same applies for score[1] in cluster 1. So this ` files_bad = np.array(files)[labels == np.argmax(scores)]` would select the higher average RMSE score (the bad image) and only get the files whose label was in that cluster. When the labels are swapped the opposite happens. If we were using the labels to directly sort good and bad your solution would work, but just not the way we currently have it implemented.

**Comment by dbuscombe-usgs** [comment]
Ah, my bad. I was reading the function at face value, not the integration with the file sorting. Thanks for double-checking. I can now close
