### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by AryanAdhau** [SatelliteShorelines/CoastSeg#277]
I am getting Value error while downloading the imagery. 

The error says value error due to invalid literal for int() with base 10: '0.0'.

Here's is the screenshot: 
![Screenshot 2024-09-17 162510](https://github.com/user-attachments/assets/bf7d449f-6b65-4b96-a1cd-fd54a8ebe07d)

Thanks

**Comment by dbuscombe-usgs** [comment]
Thanks @AryanAdhau  for this. The developer team is taking a break at the moment, and will be back in a few weeks to work on this issue. This is nor something we have encountered before. In the meantime, if you provided your ROI, shoreline, transect and any other relevant files, we can better troubleshoot the issue.

**Comment by AryanAdhau** [comment]
Thanks @dbuscombe-usgs for helping out. The information is as follows:

ROI: ID oqt4

Shoreline details:

ID: onm18
Mean Sig Waveheight: 1.687268
Tidal Range: 2.423294
Erodibility: High
River: moderate river discharge
Sinuosity: straight
Slope: sloping
Turbid: clear
CSU_ID: 20194

Transect  details

Id: region_8_1182
Slope: 0.06
Distance btw slope and transect: 0.0
Transect (x,y):(-121.809815,36.703034)
Nearest Slope (x,y):(-121.809805,36.703159)

Now the error is Attempt 3/3 failed with error: ValueError
invalid literal for int() with base 10: '1.1'

However, I tried to change the ROI and shoreline but the error is same everywhere for all coastlines.

Cheers, 
Aryan

**Comment by naresh-341** [comment]
I am facing the same issue, hey @AryanAdhau did you find a way to resolve it?

**Comment by 2320sharon** [comment]
Hi @AryanAdhau and @naresh-341 thank you both for reporting your issues. We found the cause of this bug and we are working on getting it fixed.

**Comment by 2320sharon** [comment]
Hi @AryanAdhau I've been testing the newest version of CoastSeg 1.2.15 this morning and its been working for me. 

In your coastseg environment can you run the commands below so we can verify you have the correct coastseg version installed:

```
conda list coastseg

conda list conda list coastsat-package
```

Ideally these should return 
```
(coastseg) C:\development\coastseg_user_copy\CoastSeg>conda list coastseg
# packages in environment at C:\Users\sf230\anaconda3\envs\coastseg:
#
# Name                    Version                   Build  Channel
coastseg                  1.2.15                  pypi_0    pypi
```


```
(coastseg) C:\development\coastseg_user_copy\CoastSeg>conda list coastsat-package
# packages in environment at C:\Users\sf230\anaconda3\envs\coastseg:
#
# Name                    Version                   Build  Channel
coastsat-package          0.1.74                   pypi_0    pypi
```

If that still doesn't work you may need to pull the latest code from github

**Comment by AryanAdhau** [comment]
Hi @2320sharon, Thank you for your help. It worked after reinstalling.

**Comment by 2320sharon** [comment]
Awesome, glad to hear it!
