### ISSUE TITLE
Speed up Download Times with JobLib and Parallel Processing

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#51]
Download speeds for the models, geojson files, and jpgs are very slow right now. Parallel processing with Joblib or another library could help speed up the download times.

Incorporate Joblib or another library to speed up the download times for:
1. CoastSat's retrieve images
2. download_url - for the Zenodo models
3.  geosjon shoreline files

**Comment by 2320sharon** [comment]
From the research I've been doing it looks like it might be a better idea to use `asyncio` and `aiohtttp` to increase the download speed. `Multithreading` using thread pools is also an option. I'm exploring both options.

**Comment by dbuscombe-usgs** [comment]
This requires refactoring CoastSat

**Comment by dbuscombe-usgs** [comment]
How far did we get with this? I remember @2320sharon looking into options, but cant remember the details. What did we learn? It doesnt seem to be a big priority ang longer so perhaps we can now close?

**Comment by 2320sharon** [comment]
I explored what it would take to speed up the workflow with joblib or threading and discovered it would take significant refactoring of the [coastsat package](https://github.com/2320sharon/coastsat_package) in order to speed up download times. When we met last we decided to let the download time speedup issue rest until we found time to refactor the [coastsat_package](https://github.com/2320sharon/coastsat_package) to make it faster.

**Comment by dbuscombe-usgs** [comment]
Ok yes I do remember that. Ok, I will close
