### ISSUE TITLE
Use New Zenodo Release to Download Global Shorelines

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#53]
The zenodo release here has a geojson file with the bounding boxes that encompasses the entirety of each shoreline for all the shorelines in the world. Use that geojson to download the corresponding geojson file with the correct shoreline.

https://zenodo.org/record/6917963#.YvEke3bMKkf

**Comment by 2320sharon** [comment]
https://zenodo.org/record/6917358#.YvJ073bMKkd are the US county-level shorelines.

**Comment by 2320sharon** [comment]
Created the logic to download the new files from Zenodo. The current issue is not all the files are on Zenodo, so I have left some of the testing files like `shorelines_bounding_boxes.csv` in the repo to make testing easier until all the files are up on Zenodo.

**Comment by dbuscombe-usgs** [comment]
Which files are not on Zenodo?

**Comment by dbuscombe-usgs** [comment]
I'm still looking into why zenodo doesnt upload all files, or otherwise why those files are not available

**Comment by dbuscombe-usgs** [comment]
- [ ] need to test the US counties zenodo release
- [ ] need to reupload the province files to zenodo using the rest API
