### ISSUE TITLE
CoastSat SDS_download.py retrieve_images exception handling

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#61]
## Bug: SDS_download.py has Bad Error Handling
CoastSat does not have specific error handling when running `download_tif` within  `retrieve _images()`. If any kind of exception occurs whether that be due to the file not being downloaded, the file not being available, or anything else the user will not know what caused the exception and be unable to fix it. Furthermore, this loop should not run 100 times as this could cause 100 unnecessary prints or requests. When I fix this bug I will create a Pull Request for CoastSat. For now, I'm leaving this here as a reminder for me to dig deeper into this issue and the best ways to solve it.

## Faulty Code
Filename: `SDS_download.py`
Function: `retrieve _images`
```
                while True:
                    try:    
                        fn_ms, fn_QA = download_tif(image_ee,ee_region,bands['ms'],fp_ms) 
                        break
                    except:
                        print('\nDownload failed, trying again...')
                        count += 1
                        if count > 100:
                            raise Exception('Too many attempts, crashed while downloading image %s'%im_meta['id'])
                        else:
                            continue
```

**Comment by dbuscombe-usgs** [comment]
I think this can now be closed
