### ISSUE TITLE
Kernel crashed during Zoo model implementation and also in `extract_shorelines_from_rois`

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#64]
Using `main` https://github.com/2320sharon/CoastSeg/commit/fc61aa7247e52f5b41f65ef28bc98e06cc399f29 and within an activated `coastseg` conda environment on Windows, I'm getting kernel crashes when running CoastSeg notebooks.

I used the default satellite list and date range and the attached ROI

![coastseg-3](https://user-images.githubusercontent.com/3596509/187010462-faedf450-9b9a-4166-8d3c-eabe957c27a8.PNG)
![coastseg-2](https://user-images.githubusercontent.com/3596509/187010463-91539002-4ed7-4197-a940-df831bc6dd61.PNG)
![coastseg-1](https://user-images.githubusercontent.com/3596509/187010466-25780a15-7187-4e05-aecc-592a9ada42c9.PNG)

The jupyter kernel died when `extract_shorelines_from_rois` got through 5% of the L8 imagery

[segmentation_data_2022-08-26__17_hr_51_min49.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437141/segmentation_data_2022-08-26__17_hr_51_min49.zip)

Possibly related, when I run `custom_map` with default settings,  and the default selected model `landsat_6229071` without GPU, and in the same region (but not the exact same ROI), my kernel dies again ....it starts to run the models, then crashes

![custommap-1](https://user-images.githubusercontent.com/3596509/187010627-f7762a70-aa95-47e0-aebc-f67fb87f4ace.PNG)
![custommap-2](https://user-images.githubusercontent.com/3596509/187010628-c2a8d0c7-c7a4-4549-8aaa-08388d544b8e.PNG)

[ID12022-08-26__17_hr_38_min20.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437145/ID12022-08-26__17_hr_38_min20.zip)

[ID02022-08-26__17_hr_38_min20.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437146/ID02022-08-26__17_hr_38_min20.zip)

[ID42022-08-26__17_hr_38_min20.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437142/ID42022-08-26__17_hr_38_min20.zip)

[ID32022-08-26__17_hr_38_min20.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437143/ID32022-08-26__17_hr_38_min20.zip)

[ID22022-08-26__17_hr_38_min20.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437144/ID22022-08-26__17_hr_38_min20.zip)

[shorelines.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9437148/shorelines.zip)

Thanks, let me know if you need more info @2320sharon

**Comment by 2320sharon** [comment]
Hmmm, its hard to tell what could be causing the issue. 
Did any error messages appear in the Anaconda prompt or console where you ran the jupyter notebook from? That would help me diagnose the issue. Also what OS did you run this on?

**Comment by 2320sharon** [comment]
@dbuscombe-usgs Are you still having issues with the notebook crashing or is it working better now?

**Comment by dbuscombe-usgs** [comment]
I haven't tried, vut we have new models coming so, let's table this one until we have the new model to test out
