### ISSUE TITLE
Draw or upload a ROI with arbitrary shape

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#66]
Currently, CoastSeg facilitates drawing square or rectangular ROIs. Often, coastlines and other features are linear and narrow, so it would be advantageous to have the ability to draw and also upload polygons consisting of more than 4 vertices to define the ROI. These would essentially be polygons of arbitrary shape.

**Comment by dbuscombe-usgs** [comment]
Can we try to make a non-rectangular ROI and use it with CoastSat? Do we get errors?

**Comment by 2320sharon** [comment]
I downloaded two non-rectangular shapes with CoastSat and the code runs fine. The only issue is that CoastSat by default converts all the user's shapes into rectangles with the `adjust_polygons()` function, so the all the outputs are always rectangles. Is this okay or should the user be able to download non-rectangular data? If the user must be able to be able to download data without it being converted to a rectangles first then CoastSat will have to be modified.

**Comment by dbuscombe-usgs** [comment]
I think this can now be closed
