### ISSUE TITLE
Create static map of available coastlines, and guidance for users to upload their own reference shoreline

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#70]
Referencing issues https://github.com/dbuscombe-usgs/CoastSeg/issues/69 and https://github.com/dbuscombe-usgs/CoastSeg/issues/53

it would be helpful to 

- [ ] create a static map of each available shoreline segment to see which regions are not covered
- [ ] post guidance to users working in regions that have no available shorelines. the guidance should include reference to existing capability of CoastSeg to upload a user-defined reference shoreline, and the geojson format that shoreline should be in

**Comment by 2320sharon** [comment]
> Referencing issues #69 and #53
> 
> it would be helpful to
> 
> * [ ]  create a static map of each available shoreline segment to see which regions are not covered
> * [ ]  post guidance to users working in regions that have no available shorelines. the guidance should include reference to existing capability of CoastSeg to upload a user-defined reference shoreline, and the geojson format that shoreline should be in

I can take care of the second task by creating a small section on the readme that links to the wiki page that will explain how to upload a shoreline. I will also create an issue template for contributing a shoreline as well.

**Comment by dbuscombe-usgs** [comment]
Update README/wiki to explain what locations have reference shorelines, and which do not
