### ISSUE TITLE
"Run model" `do_crf` flag needed for `do_seg()`

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#76]
### the bug

In `app.ipynb` using all the default settings and using a small ROI, when I hit 'Run Model', I get the following error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/anaconda3/envs/coastseg_test/lib/python3.8/site-packages/ipywidgets/widgets/widget_output.py:103, in Output.capture.<locals>.capture_decorator.<locals>.inner(*args, **kwargs)
    101     self.clear_output(*clear_args, **clear_kwargs)
    102 with self:
--> 103     return func(*args, **kwargs)

Input In [8], in run_model_button_clicked(button)
    108 metadatadict=zoo_model.get_metadatadict(Ww,config_files, model_types)
    109 # # Compute the segmentation
--> 110 zoo_model.compute_segmentation(model_dict["sample_direc"], model_list, metadatadict)

File /media/marda/ExtraDrive1/satellites/CoastSeg/CoastSeg/zoo_model_module.py:44, in Zoo_Model.compute_segmentation(self, sample_direc, model_list, metadatadict)
     42 # Compute the segmentation for each of the files
     43 for f in tqdm(sample_filenames):
---> 44     do_seg(
     45         f,
     46         model_list,
     47         metadatadict,
     48         sample_direc,
     49         self.NCLASSES,
     50         self.N_DATA_BANDS,
     51         self.TARGET_SIZE,
     52         TESTTIMEAUG,
     53         WRITE_MODELMETADATA)

TypeError: do_seg() missing 1 required positional argument: 'do_crf'
```

### Steps To Reproduce
1. from activated `coastseg_test` env, run `jupyter notebook`
2. run app.ipynb
3. run all cells with defualt values and hit 'run model' button

### Expected behavior
This just requires a new flag `do_crf`. If True, the `crf_refine` function will be used in `do_seg` (part of doodleverse_utils). Should be "False" by default, with an option to set to true. Call it "Use CRF post-processing"

**Comment by dbuscombe-usgs** [comment]
see https://github.com/Doodleverse/doodleverse_utils/blob/main/doodleverse_utils/prediction_imports.py#L268

**Comment by 2320sharon** [comment]
I have already implemented this change in my fork of CoastSeg in the main branch. You should be able to update your branch to have this fixed.
You can see I've added the new `do_crf` parameter in the `do_seg` function call in `compute_segmentation`https://github.com/2320sharon/CoastSeg/blob/main/CoastSeg/zoo_model_module.py.
Currently, it defauls to True and there isn't a way for the user to change it. I will work on adding a control for it and modify it so it defaults to False.

**Comment by 2320sharon** [comment]
I've added in the new control for the CRF post processing in my main branch
