### ISSUE TITLE
Create a feature to allow users to upload their own reference shorelines

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#83]
Currently, there is no way for users to upload their own shorelines if the shorelines are not in a zendo release that can be downloaded. I would like a workflow to be created that would allow users to upload a  geojson file containing their shoreline. If the shoreline is too large an error message would be displayed to the user.  I think a button that opens a file selection widget that will allow the user to select their shoreline geojson file from the command line will be best.

**Comment by dbuscombe-usgs** [comment]
Good idea
