### ISSUE TITLE
Config File for ROIs, bbox and settings

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#85]
**Describe the solution you'd like**
Currently, a user must use all the interactive prompts in order to select an ROI, download it, extract shorelines, and run models on the data.  There should be a series of config files and a new script that would allow the user to download all the data they want without ever interacting with the jupyter notebook. Having a series of config files to configure machine learning processes is a recommended best practice in the paper ["Operationalizing Machine Learning: An Interview Study"](https://arxiv.org/abs/2209.09125) as it makes experiments more reproducible and minimizes user error due to incorrect inputs. I propose splitting these settings across 4 different config files to promote a degree of data separation as well as to prevent the user accidentally from modifying settings they don't want to change. This would also make the config files easier to understand instead of a single giant config file.

I recommend creating 4 config files: preprocess_settings, model_settings, ROI_settings, and shoreline_settings. The preprocess_settings config file would control the preprocess settings for coastsat which control data quality settings like cloud cover threshold, controls for CoastSat's machine learning models, and more. The model_settings would control which of the models from [segmentation_zoo](https://github.com/Doodleverse/segmentation_zoo) was selected, whether to use CRF postprocessing and other settings related to running the models on the downloaded data.  The  ROI settings config file would control the number of ROIs requested, the location, dates, and satellites of the requested ROIs. Lastly, the shoreline settings config file would control which ROI files had their shorelines extracted, the transects used, and more.

**Documentation**
In order for the user to know how to properly use the config files there would need to be associated documentation that explains what each field in the config file means as well a sample config file. Another page with a sample config and script with outputs would be helpful for showing the user what to expect from their outputs.

**Feedback Requested**
@dbuscombe-usgs @ebgoldstein 
Do you think having 4 config files is too much?

**Comment by ebgoldstein** [comment]
yeah, i would lump it all in 1 config file.. the config for `gym` could really be thought of as multiple configs, it's just all in a single json and then broken down into separate headings in the documentation.. i say this because some configs matter to make_datasets, and are unused in train_model (and vice versa)..... 

Also, i would try to make some wise default choices, so a user could not set most of the configs and rely on the defaults if they just wanted to dip their toes in the water...

**Comment by dbuscombe-usgs** [comment]
I like the idea of breaking it up into 2 files,  to reflect the two parallel workflow of zoo and coastsat and to make experiments easier. One would set all the coastsat variables, and would include roi, preprocess, and shoreline. The other would control application choices associated with the zoo model. I agree with Evan that smart defaults would be desirable

**Comment by 2320sharon** [comment]
> If it were me, I would lump it all in 1 config file.. the config for `gym` could really be thought of as multiple configs, it's just all in a single json and then broken down into separate headings in the documentation.. i say this because some configs matter to make_datasets, and are unused in train_model (and vice versa).....
> 
> Also, i would try to make some wise default choices, so a user could not set most of the configs and rely on the defaults if they just wanted to dip their toes in the water...

I think starting off with config file(s) with a default configuration would be smart so the user is not overwhelmed by having to learn all the fields. Maybe having a few examples for different configurations could be useful too.

**Comment by 2320sharon** [comment]
> I like the idea of breaking it up into 2 files, to reflect the two parallel workflow of zoo and coastsat and to make experiments easier. One would set all the coastsat variables, and would include roi, preprocess, and shoreline. The other would control application choices associated with the zoo model. I agree with Evan that smart defaults would be desirable

I like the idea of splitting it up into two files to keep the data collection and the model application process separate. Plus seeing two config files is less intimidating than 4 files.
