### ISSUE TITLE
pydensecrf no longer a dependency for Gym or Zoo

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#91]
As of release [v0.0.14](https://pypi.org/manage/project/doodleverse-utils/release/0.0.14/) doodleverse-utils no longer has `pydensecrf` as a dependency. It is a rarely used function that affords little benefit, and it is not available on pip which could cause deployment problems. See https://github.com/Doodleverse/doodleverse_utils/issues/16

Update [src/coastseg/UI_models.py](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/src/coastseg/UI_models.py) to remove `use_CRF` option

Update [src/coastseg/zoo_model.py](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/src/coastseg/zoo_model.py) to remove `do_crf` option

Update [/refactored_custom_map_official.ipynb](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/refactored_custom_map_official.ipynb) to remove reference to CRF

Update [/custom_map.ipynb](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/custom_map.ipynb) to remove reference to CRF

**Comment by 2320sharon** [comment]
- [ ] Update [src/coastseg/UI_models.py](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/src/coastseg/UI_models.py) to remove use_CRF option
- [ ] 
- [ ] Update [src/coastseg/zoo_model.py](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/src/coastseg/zoo_model.py) to remove do_crf option
- [ ] 
- [ ] Update [/refactored_custom_map_official.ipynb](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/refactored_custom_map_official.ipynb) to remove reference to CRF
- [ ] 
- [ ] Update [/custom_map.ipynb](https://github.com/SatelliteShorelines/CoastSeg/blob/5cf7a250d75a09ed01c5333957cad013396cf355/custom_map.ipynb) to remove reference to CRF
