### ISSUE TITLE
Zoo now has new Zenodo model and better (and faster) programmatic access to those models. Suggestions for how to incorporate in CoastSeg

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#92]
**Updated code**
See https://github.com/Doodleverse/segmentation_zoo/issues/15 and the rewritten [select_model_and_batch_process_folder.py](https://github.com/Doodleverse/segmentation_zoo/blob/main/scripts/select_model_and_batch_process_folder.py) script

CoastSeg could be modified along these lines

**Updated models**
The wiki has been updated with details of all 5 of the new available models on Zenodo  https://github.com/Doodleverse/segmentation_zoo/wiki/4_Models#landsatsentinel-2-models

Note that these are only for 4-class (water, whitewater, sediment, other)

I am now working on the simpler 2-class (water, nowater) models

According to the changes I suggested in https://github.com/SatelliteShorelines/CoastSeg/issues/89, the forthcoming 2-class models should be made available in `SDS_coastsat_classifier.ipynb` only, and both the 4-class and the 2-class models should be made available in `SDS_unet_classifier.ipynb`

**Comment by 2320sharon** [comment]
I've implemented a function to convert RGB imagery to MNDWI and NDWI imagery in the commit https://github.com/SatelliteShorelines/CoastSeg/commit/8c6dc68bfc9e21c0c203adc3d0ef5602fa4772ab
When the user clicks run model the RGB directory along with the NIR and SWIR directories are automatically found and used to create a new directory 'MNDWI '/'NDWI' which contains the newly created imagery.
