### ISSUE TITLE
Integrate new Zenodo Models

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#94]
All these zenodo releases seem to use the new format specified in #92
- [x] 4-class RGB model release: https://zenodo.org/record/6950472#.Y353LzPMLRY
- [x] 4-class RGB+NIR+SWIR model release: https://zenodo.org/record/7344606#.Y36NSjPMLRY
- [x] 4-class NDWI model release: https://zenodo.org/record/7352859#.Y36yqDPMLRY
- [x] 4-class MNDWI model release: https://zenodo.org/record/7352850#.Y3600jPMLRY
- [x]  4-class RGB+NIR+SWIR model release: https://zenodo.org/record/7344606#.Y36NSjPMLRY

**Comment by dbuscombe-usgs** [comment]
Hi Sharon, yes these are 4 out of the 5 new models. However, I would suggest that (at least for now) we run only with the first two

- [ ] 4-class RGB model release: https://zenodo.org/record/6950472#.Y353LzPMLRY
- [ ] 4-class RGB+NIR+SWIR model release: https://zenodo.org/record/7344606#.Y36NSjPMLRY

That is a decision based on the validation statistics for the 4 models

This is the best RGB model:
![sat4class_rgb_512_v1_trainhist_32](https://user-images.githubusercontent.com/3596509/204377823-674fa692-9f5f-406b-b6c1-0ef86bb4473f.png)

This is the best "5d" (5 band R+G+B+NIR+SWIR) model:
![sat4class_5d_512_v1_trainhist_32](https://user-images.githubusercontent.com/3596509/204378017-f017de49-456b-416c-89cb-77f5e2cfc4fc.png)

The NDWI and MNDWI models are not quite as good. Here's the best NDWI:
![sat4class_ndwi_512_v6_trainhist_32](https://user-images.githubusercontent.com/3596509/204378244-d0004a6f-3abc-404b-ae8f-68fa80dcfd75.png)

and best MNDWI
![sat4class_mndwi_512_v1_trainhist_32](https://user-images.githubusercontent.com/3596509/204378399-e09db416-92bf-4181-aff6-c6bf1b487544.png)

So, RGB and 5d models are superior

Also note that there will be additional 2-class models soon .... at least 1 or 2 will be incorporated into CoastSeg

**Comment by 2320sharon** [comment]
I'll comment out the models that don't perform as well for now. 
Thanks for including the validation statistics.

**Comment by 2320sharon** [comment]
@dbuscombe-usgs Do you have a script or function that prepares the 5d imagery for the model? I'm hoping to integrate it into coastseg.

**Comment by dbuscombe-usgs** [comment]
Yes, right now in Gym we have [preprocess_data.py](https://github.com/Doodleverse/segmentation_gym/blob/main/utils/preprocess_data.py) which is a wrapper to the doodleverse-utils function you could use for the 5-band images [merge_nd_inputs4pred.py](https://github.com/Doodleverse/doodleverse_utils/blob/main/doodleverse_utils/merge_nd_inputs4pred.py)

I'm also planning on putting together an example Huggingface space we can test for 5-band models (like I did for the RGB model [here](https://huggingface.co/spaces/dbuscombe/sat_RGB_4class_6950472)) ... more soon

**Comment by 2320sharon** [comment]
Thanks for the help. I'll dig into `merge_nd_inputs4pred.py` and see how the 5 band imagery are prepared and ask any questions I have here.

**Comment by dbuscombe-usgs** [comment]
Hold fire @2320sharon -- I tested `merge_nd_inputs4pred.py` and found bugs 

They are hopefully fixed in https://github.com/Doodleverse/doodleverse_utils/commit/c08bef2da6d4c887e44b491e42ec733944dc3460

please use version v0.0.15 https://pypi.org/project/doodleverse-utils/

**Comment by dbuscombe-usgs** [comment]
here are a set of (input and output) files you can use to test the `merge_nd_inputs4pred.py` function

[example_sat_images.zip](https://github.com/SatelliteShorelines/CoastSeg/files/10108926/example_sat_images.zip)
